######################################################################
# Automatically generated by qmake (2.01a) jue ago 7 14:13:13 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += BBEditorWidget.h ../src/BBResource.h
SOURCES += BBEditorWidget.cpp main.cpp ../src/BBResource.cpp
